language: python
dist: xenial
python:
  - 3.7
install:
  - pip install codecov -r requires/development.txt
script:
  - nosetests
  - python setup.py build_sphinx
  - python setup.py check
  - flake8
after_success:
  - codecov
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  on:
    python: 3.7
    tags: true
    all_branches: true
  user: sprockets
  password:
    secure: BdTGYPioHV/pxNTKnS1pxBFu4cqJHHNu7VtYebWDVKBtaavYSpyFh3Vbfpx5RpTjJbMHjmJBtGbsbndU8N8BwxAcDrWfvxYtV7IjaPonZCzBzAtieSAwR7qrgb8lPc3Z1qUSjK80zl3PgNTph+0Y2c2wJX84odq689y9nNsV3t9sM+91SqGN5zonuFlM7JlyR0ihJzQVuGq5Wnq66qPd8yErPQjeI3nTPHnRRSLrwCBhengncRKRng/HmJPQ0Ywu84Mcvu3qlOq+Km2mFWAdzjn9dXRhFsHYupzKhg45WFL2jlBpPxeH2J9WTzFTGcTdOSQ3wnfw1TvxNLHcsCAK+QH1WJjuNR4KybwRP142EZ7L1ys4ANQCSe5wcw4FRBqwhMjYd96MiSW5Mp7AnN0s/FBReJJcXccUyVkgENTuyqyM63o7YX9jySp8jRmRtnOkz3K0pydM1HHSY0wn8IC8ElFbVu4OhevOr/w0ZqLwot/lLwTgQgT4qhGDB9PGRd1eHTx2T2GDhXN6pCIXm7Whk5piIsOZoSk1xtzAEoq05bPB5hPfBjoW41uC2W/q2RlKLI/yp9LgNayrUSmNcXCrZ9L37b2aO5UN16yzM4AUilkLteiOMJOze+KMerlwsqoMAPJvoed1ioTd8IPQDFUy/2TQvYKAHGPMkJjenXW540E=
